namespace RhinoIllustratorBridge.Core
{
    public static class JsxTemplates
    {
        public const string GetArtboardsJs = @"
(function() {
    try {
        if (app.documents.length === 0) return 'ERROR:No document is open in Illustrator.';
        var doc = app.activeDocument;
        var list = [];
        var PT2MM = 0.3527777778;
        for (var i = 0; i < doc.artboards.length; i++) {
            var ab = doc.artboards[i];
            var rect = ab.artboardRect;
            list.push({
                'name': ab.name,
                'width_mm': (rect[2] - rect[0]) * PT2MM,
                'height_mm': (rect[1] - rect[3]) * PT2MM,
                'left_mm': rect[0] * PT2MM,
                'top_mm': rect[1] * PT2MM,
                'right_mm': rect[2] * PT2MM,
                'bottom_mm': rect[3] * PT2MM
            });
        }
        var jsonStr = '[';
        for (var k = 0; k < list.length; k++) {
            var obj = list[k];
            jsonStr += '{';
            jsonStr += '""name"":""' + obj.name.replace(/\\/g, '\\\\').replace(/""/g, '\\""') + '"",';
            jsonStr += '""width_mm"":' + obj.width_mm + ',';
            jsonStr += '""height_mm"":' + obj.height_mm + ',';
            jsonStr += '""left_mm"":' + obj.left_mm + ',';
            jsonStr += '""top_mm"":' + obj.top_mm + ',';
            jsonStr += '""right_mm"":' + obj.right_mm + ',';
            jsonStr += '""bottom_mm"":' + obj.bottom_mm;
            jsonStr += '}';
            if (k < list.length - 1) jsonStr += ',';
        }
        jsonStr += ']';
        return jsonStr;
    } catch(e) {
        return 'ERROR:' + e.toString();
    }
})()
";

        public const string UpdateCurvesJs = @"
// _rhino_sync_update.jsx (auto-generated by Rhino Direct Sync)
(function() {
    var resultFile = new File(""__RESULT_PATH__"");
    try {
        var inPath = ""__CURVES_PATH__"";
        var file = new File(inPath);
        if (!file.exists) { writeResult(resultFile, ""ERROR:Curves file not found at "" + inPath); return; }
        file.encoding = ""UTF-8"";
        file.open(""r"");
        var raw = file.read();
        file.close();

        if (!raw || raw.length === 0) { writeResult(resultFile, ""ERROR:Curves JSON empty.""); return; }

        var data;
        try {
            data = eval(""("" + raw + "")"");
        } catch(err) {
            writeResult(resultFile, ""ERROR:Failed to parse JSON: "" + err.toString());
            return;
        }

        if (!data || data.length === 0) { writeResult(resultFile, ""ERROR:No curve data found.""); return; }

        var doc = (app.documents.length > 0) ? app.activeDocument : app.documents.add();

        function ensureLayer(pathName) {
            var layer = doc;
            var names = pathName.split(""::"");
            for (var i = 0; i < names.length; i++) {
                try { layer = layer.layers.getByName(names[i]); }
                catch (e) { layer = layer.layers.add(); layer.name = names[i]; }
            }
            return layer;
        }
        function mmToPt(mm) { return mm * 2.8346456693; }
        function applyStroke(item, color, width, linetype) {
            if (!item) return;
            item.stroked = true;
            item.filled  = false;
            if (color && color.length === 3) {
                var c = new RGBColor();
                c.red = color[0]; c.green = color[1]; c.blue = color[2];
                item.strokeColor = c;
            }
            item.strokeWidth = (typeof width === ""number"") ? width : 1.0;
            var lt = linetype ? linetype.toLowerCase() : """";
            if      (lt === ""dashed"")                      { item.strokeDashes = [6, 3]; }
            else if (lt === ""dots"")                        { item.strokeDashes = [1, 3]; }
            else if (lt === ""hidden"")                      { item.strokeDashes = [2, 2]; }
            else if (lt === ""dashdot"" || lt === ""center"")  { item.strokeDashes = [6, 3, 0, 3]; }
            else                                           { item.strokeDashes = []; }
        }

        var totalCurves = 0;

        var itemMap = {};
        for (var piIdx = 0; piIdx < doc.pageItems.length; piIdx++) {
            var pitm = doc.pageItems[piIdx];
            if (pitm.name) itemMap[pitm.name] = pitm;
        }

        for (var i = 0; i < data.length; i++) {
            var abData = data[i];
            var curves = abData.curves;
            if (!curves) continue;

            for (var j = 0; j < curves.length; j++) {
                var curve = curves[j];
                if (!curve.layer) continue;
                var targetLayer = ensureLayer(curve.layer);

                var group = null;
                if (curve.group_id) {
                    var gid = ""group_"" + curve.group_id;
                    group = itemMap[gid];
                    if (group && group.typename !== ""GroupItem"") group = null;
                    if (!group) {
                        try {
                            group = targetLayer.groupItems.add();
                            group.name = gid;
                            itemMap[gid] = group;
                        } catch(e) {}
                    }
                }
                var parentContainer = group || targetLayer;

                // --- Text ---
                if (curve.type === ""text"") {
                    try {
                        if (curve.id) {
                            var et = itemMap[curve.id];
                            if (et) { try { et.remove(); } catch(e){} }
                        }
                        var textRef = targetLayer.textFrames.add();
                        textRef.contents = curve.text;
                        var fontSize = curve.height ? mmToPt(curve.height) : 12;
                        textRef.textRange.characterAttributes.size = fontSize;
                        if (curve.color && curve.color.length === 3) {
                            var tc = new RGBColor();
                            tc.red = curve.color[0]; tc.green = curve.color[1]; tc.blue = curve.color[2];
                            textRef.textRange.characterAttributes.fillColor = tc;
                        }
                        if (curve.font) {
                            try { textRef.textRange.characterAttributes.textFont = app.textFonts.getByName(curve.font); } catch(e) {}
                        }
                        if (curve.justification) {
                            var just = curve.justification.toLowerCase();
                            if (just === ""center"") textRef.textRange.paragraphAttributes.justification = Justification.CENTER;
                            else if (just === ""right"") textRef.textRange.paragraphAttributes.justification = Justification.RIGHT;
                            else textRef.textRange.paragraphAttributes.justification = Justification.LEFT;
                        }
                        var tx = mmToPt(curve.point[0]);
                        var baselineY = -mmToPt(curve.point[1]);
                        textRef.position = [0, 0];
                        var dx = 0, dy = 0;
                        try { var anch = textRef.anchor; dx = -anch[0]; dy = -anch[1]; }
                        catch(ae) { dy = fontSize * 0.8; }
                        textRef.position = [tx + dx, baselineY + dy];
                        if (curve.id) { textRef.name = curve.id; itemMap[curve.id] = textRef; }
                        if (group) textRef.move(group, ElementPlacement.PLACEATEND);
                    } catch (e) {}
                    totalCurves++;
                    continue;
                }

                // --- Picture ---
                if (curve.type === ""picture"" && curve.image) {
                    try {
                        var imgFile = new File(curve.image);
                        if (imgFile.exists) {
                            if (curve.id) { 
                                var ep = itemMap[curve.id]; 
                                if (ep) { try { ep.remove(); } catch(e){} } 
                            }
                            var placed = targetLayer.placedItems.add();
                            placed.file = imgFile;
                            placed.position = [mmToPt(curve.left), -mmToPt(curve.top)];
                            placed.width = mmToPt(curve.width);
                            placed.height = mmToPt(curve.height);
                            if (curve.id) { placed.name = curve.id; itemMap[curve.id] = placed; }
                            if (group) placed.move(group, ElementPlacement.PLACEATEND);
                        }
                    } catch (e) {}
                    totalCurves++;
                    continue;
                }

                // --- Path items ---
                if (!curve.points || curve.points.length === 0) continue;

                var pts = [];
                for (var k = 0; k < curve.points.length; k++) {
                    pts.push([mmToPt(curve.points[k][0]), -mmToPt(curve.points[k][1])]);
                }

                var existingPath = null;
                if (curve.id) {
                    existingPath = itemMap[curve.id];
                }

                if (existingPath && existingPath.typename === ""PathItem"") {
                    if (curve.type === ""circle"" || curve.type === ""ellipse"") {
                        var cx2 = pts[0][0], cy2 = pts[0][1];
                        var r2 = (curve.radius !== undefined) ? mmToPt(curve.radius) : mmToPt(1);
                        var nc = targetLayer.pathItems.ellipse(cy2+r2, cx2-r2, r2*2, r2*2);
                        nc.name = curve.id; nc.closed = true;
                        itemMap[curve.id] = nc;
                        nc.filled = existingPath.filled;
                        if (existingPath.filled) nc.fillColor = existingPath.fillColor;
                        nc.stroked = existingPath.stroked;
                        if (existingPath.stroked) { nc.strokeColor = existingPath.strokeColor; nc.strokeWidth = existingPath.strokeWidth; nc.strokeDashes = existingPath.strokeDashes; }
                        if (group) nc.move(group, ElementPlacement.PLACEATEND);
                        existingPath.remove();
                    } else {
                        if (group && existingPath.parent !== group) { try { existingPath.move(group, ElementPlacement.PLACEATEND); } catch(e) {} }
                        else if (!group && existingPath.parent !== targetLayer) { try { existingPath.move(targetLayer, ElementPlacement.PLACEATEND); } catch(e) {} }
                        
                        var pp = existingPath.pathPoints;
                        while (pp.length > pts.length) { pp[pp.length-1].remove(); }
                        for (var m = 0; m < pp.length; m++) { pp[m].anchor = pts[m]; pp[m].leftDirection = pts[m]; pp[m].rightDirection = pts[m]; }
                        for (var m = pp.length; m < pts.length; m++) { var npt = pp.add(); npt.anchor = pts[m]; npt.leftDirection = pts[m]; npt.rightDirection = pts[m]; npt.pointType = PointType.CORNER; }
                        existingPath.closed = (curve.closed === true);
                    }
                    totalCurves++;
                    continue;
                }

                if ((curve.type === ""circle"" || curve.type === ""ellipse"") && pts.length >= 1) {
                    var cx3 = pts[0][0], cy3 = pts[0][1];
                    var r3 = (curve.radius !== undefined) ? mmToPt(curve.radius) : mmToPt(1);
                    var circ = targetLayer.pathItems.ellipse(cy3+r3, cx3-r3, r3*2, r3*2);
                    if (curve.id) { circ.name = curve.id; itemMap[curve.id] = circ; }
                    circ.closed = true;
                    applyStroke(circ, curve.color, curve.width, curve.linetype);
                    if (group) circ.move(group, ElementPlacement.PLACEATEND);
                } else if (pts.length >= 2) {
                    var poly = targetLayer.pathItems.add();
                    if (curve.id) { poly.name = curve.id; itemMap[curve.id] = poly; }
                    try {
                        for (var m = 0; m < pts.length; m++) {
                            var npt = poly.pathPoints.add();
                            npt.anchor = [pts[m][0], pts[m][1]];
                            npt.leftDirection = npt.anchor;
                            npt.rightDirection = npt.anchor;
                            npt.pointType = PointType.CORNER;
                        }
                        var isFill = (curve.type === ""hatch_solid"" || curve.type === ""hatch"");
                        if (isFill) {
                            poly.closed = true; poly.filled = true; poly.stroked = false;
                            var fc = curve.fill_color || curve.color;
                            if (fc && fc.length === 3) { var fr = new RGBColor(); fr.red = fc[0]; fr.green = fc[1]; fr.blue = fc[2]; poly.fillColor = fr; }
                        } else {
                            poly.filled = false; poly.stroked = true;
                            poly.closed = (curve.closed === true);
                            applyStroke(poly, curve.color, curve.width, curve.linetype);
                        }
                        if (group) poly.move(group, ElementPlacement.PLACEATEND);
                    } catch(e) {}
                }
                totalCurves++;
            }
        }
        app.redraw();
        writeResult(resultFile, ""SUCCESS:"" + totalCurves);
    } catch(e) {
        writeResult(resultFile, ""ERROR:"" + e.toString());
    }
})();

function writeResult(f, msg) {
    f.encoding = ""UTF-8"";
    f.open(""w"");
    f.write(msg);
    f.close();
}
";
    }
}
